CREATE TABLE csdn(
    ID INTEGER KEY NOT NULL,
	FINGER CHAR(20) NOT NULL,
	LABEL CHAR(50),
	READ_TIMES NUMBER,
	SUPPORT NUMBER,
	TITLE TEXT NOT NULL,
	HREF CHAR(150) NOT NULL,
	AUTHOR CHAR(50),
	TIME TEXT NOT NULL,
)

CREATE TABLE jobbole(
    ID INTEGER KEY NOT NULL,
	FINGER CHAR(20) NOT NULL,
	TITLE TEXT NOT NULL,
	HREF CHAR(150) NOT NULL,
	SUMMARY TEXT,
	LABEL CHAR(50),
	TIME TEXT NOT NULL,
)

CREATE TABLE segmentfault(
    ID INTEGER KEY NOT NULL,
	FINGER CHAR(20) NOT NULL,
	TITLE TEXT NOT NULL,
	HREF CHAR(150) NOT NULL,
	AUTHOR CHAR(50),
	LABEL CHAR(50),
	SUPPORT NUMBER,
	TIME TEXT NOT NULL,
)